export * from './Contacto';
export * from './Inicio';
export * from './About';
export * from './Skills';
export * from './Proyectos';
export * from './Proyecto';
export * from './layout';
export * from './Error404';
export * from './Loading';